defaults:
  - train_envs: endless_all
actors:
  hero:
    agent: td3
    reward:
      entry_point: reward.valeo_action:ValeoAction
      kwargs: {}
    terminal:
      entry_point: terminal.valeo_no_det_px:ValeoNoDetPx
      kwargs: {}
ev_id: hero
carla_sh_path: /home/dell/software/CARLA_0.9.10/CarlaUE4.sh
total_timesteps: 1e8
seed: 2025
kill_running: true
dummy: false
wb_project: sb3_baselines
wb_name: "TD3"
wb_notes: null
wb_tags: null
curriculum: false